version: '3'
services:
  nextjs_app:
    build:
      context: ./nextjs_app
      dockerfile: Dockerfile
    volumes:
      - ./nextjs_app/build:/app/nextjs_app/build
      - /app/nextjs_app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

  expressjs_app:
    build:
      context: ./expressjs_app
      dockerfile: Dockerfile
    volumes:
      - ./expressjs_app:/app/expressjs_app
      - ./expressjs_app/dist:/app/expressjs_app/dist
      - /app/expressjs_app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - 27017:27017
